"""empty message

Revision ID: 8faeb481cc03
Revises: a79e12491293
Create Date: 2022-05-28 04:26:05.175421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8faeb481cc03'
down_revision = 'a79e12491293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'website_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'website_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
